SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION T1
    SELECT
        SUM(Cena)
    FROM
        Wycieczki
-- STEP 1 RUN ABOVE

    UPDATE Bilety
        SET cena = cena * 2
    WHERE
        kraj = 'Ateny'
-- STEP 3 RUN BETWEEN 1 AND 3

COMMIT TRANSACTION T1
